services:
  people-management-api:
    container_name: people-management-api
    image: people-management-api
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5052:80"
    depends_on:
      - people-management-db

  people-management-db:
    container_name: people-management-db
    image: mssql-graph-db
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - 5432:1433
    environment:
      - SA_PASSWORD=Yukon900
      - ACCEPT_EULA=Y

networks:
  default:
    # use the default network of the karma container
    external: true
    name: karma_default