version: "3.9"

services:
  people-management-api:
    container_name: people-management-api
    image: people-management-api
    build:
      context: ../Api
      dockerfile: Dockerfile
    ports:
      - "5052:80"

networks:
  default:
    # use the default network of the karma container
    external: true
    name: karma_docker_api_default